### ISSUE TITLE
请问何语言怎么算1+1

### ISSUE THREAD

**Issue by KarisAya** [kifuan/helang#57]
这是程序：

u8 i;
i=1+1;
print i;

这是报错：

PS C:\GIT\helang\helang> python main.py
Traceback (most recent call last):
  File "C:\GIT\helang\helang\main.py", line 9, in <module>
    parser = Parser(lexer.lex())
  File "C:\GIT\helang\helang\helang\lexer.py", line 35, in lex
    Lexer.methods.apply(self._state, self, tokens)
  File "C:\GIT\helang\helang\helang\enum_method.py", line 15, in apply
    return self._methods[enum](*args, **kwargs)
  File "C:\GIT\helang\helang\helang\lexer.py", line 107, in _lex_increment
    raise BadTokenException('only ++ operator is expected, as the King He has NOT written single +')
helang.exceptions.BadTokenException: only ++ operator is expected, as the King He has NOT written single +

**Comment by kifuan** [comment]
> the King He has NOT written single +

你没看报错吗，何圣没写过单个的加号

**Comment by kifuan** [comment]
我同学是不会算1+1的，他只会开灯😋

**Comment by KarisAya** [comment]
😋

**Comment by kifuan** [comment]
我同学会算了，你需要这样写（参考README.MD中的自增运算）：

```c
u8 a = 1;
a++;
print a;
// 2
```
